name: msgbits

services:
  frontend:
    # image: ${DOCKER_REPO}/frontend:${GITHUB_SHA}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env.production  # Add this line  
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge