name: Build, Push, and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Create .env.production file
      run: |
        echo "${{ secrets.ENV_PROD }}" > .env.production

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push with Docker Compose
      env:
        DOCKER_REPO: ${{ secrets.DOCKERHUB_USERNAME }}
        GITHUB_SHA: ${{ github.sha }}
      run: |
        # Pull Redis image explicitly
        docker pull redis:7.0-alpine

        # Build all services
        docker compose build

        # Tag and push each service
        docker compose config --format json | jq -r '.services | to_entries[] | .key as $service | .value.image // .value.name | select(. != null) | [$service, .] | @tsv' | while read service image; do
          
          if [ "$service" = "redis" ]; then
            # For Redis, use the pulled image
            image="redis:7.0-alpine"
          else
            # For other services (like backend), use the built image
            image="${DOCKER_REPO}/${service}"
          fi

          # Tag with SHA
          docker tag $image ${DOCKER_REPO}/${service}:${GITHUB_SHA}
          docker push ${DOCKER_REPO}/${service}:${GITHUB_SHA}
          
          # Tag as latest
          docker tag $image ${DOCKER_REPO}/${service}:latest
          docker push ${DOCKER_REPO}/${service}:latest
        done


  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: store private key
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        

    - name: Deploy to EC2 with Docker Compose
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ubuntu
        DOCKER_REPO: ${{ secrets.DOCKERHUB_USERNAME }}
        GITHUB_SHA: ${{ github.sha }}
      run: |
        ssh  -o IdentityFile=<(echo "$PRIVATE_KEY") \
         -o StrictHostKeyChecking=no ${USER}@${HOST} "
          export DOCKER_REPO=${DOCKER_REPO}
          export GITHUB_SHA=${GITHUB_SHA}
          docker-compose pull
          docker-compose up -d
          docker system prune -af
        "